version: '3'

services:
  backend:
    container_name: backend
    build: .
    depends_on:
      - kafka
      - zookeeper
      - postgres
    networks:
      - app

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: MARKOV
    ports:
      - "5432:5432"
    networks:
      - app

  kafka:
    container_name: kafka
    image: bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - app

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    networks:
      - app


networks:
  app:
    driver: bridge
