version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: MARKOV
    ports:
      - '5432:5432'
    networks:
      - blps
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    container_name: kafka
    image: bitnami/kafka
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ADVERTISED_HOST_NAME: 'kafka'
    networks:
      - blps
    volumes:
      - kafka_data:/bitnami/kafka
    ports:
      - '9092:9092'

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    networks:
      - blps
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    volumes:
      - zookeeper_data:/bitnami/zookeeper

networks:
  blps:
    driver: bridge

volumes:
  kafka_data:
  zookeeper_data:
  postgres_data:
