version: '3'

services:
  backend:
    build: .
    depends_on:
      - kafka
      - zookeeper
      - postgres
    networks:
      - app

  postgres:
    image: postgres
    networks:
      - app

  kafka:
    image: bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - app

  zookeeper:
    image: bitnami/zookeeper
    networks:
      - app


networks:
  app:
    driver: bridge
