spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: s286528
    password:
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: postgresql