server:
  error:
    include-stacktrace: always
spring:
  #  profiles:
  #    default: dev
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: MARKOV
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      #ddl-auto: update
      ddl-auto: create
    generate-ddl: true
    database: postgresql

token:
  jwtSecret: ja5XKcJV478PZ7z91ILt0EYlHieM4clnKzwW1ZdKw
  jwtExpirationMs: 36000000
