spring:
  profiles:
    active: @spring.profiles.active@
    default: dev
  datasource:
    username: s286528
    password: npe290
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
#            ddl-auto: update
      ddl-auto: create
    generate-ddl: true
    database: postgresql

token:
  jwtSecret: ja5XKcJV478PZ7z91ILt0EYlHieM4clnKzwW1ZdKw
  jwtExpirationMs: 36000000
