server:
  error:
    include-stacktrace: always
  port: 8081
spring:
  kafka:
    consumer:
      group-id: greetings
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9093
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
